///
/// @Generated by Mockolo
///


@testable import Coiner
import Foundation


class AssetsStoreProtocolMock: AssetsStoreProtocol {
    init() { }


    private(set) var addCallCount = 0
    var addHandler: ((AssetEntity) -> ())?
    func add(asset: AssetEntity)  {
        addCallCount += 1
        if let addHandler = addHandler {
            addHandler(asset)
        }
        
    }

    private(set) var getCallCount = 0
    var getHandler: (() -> ([AssetEntity]))?
    func get() -> [AssetEntity] {
        getCallCount += 1
        if let getHandler = getHandler {
            return getHandler()
        }
        return [AssetEntity]()
    }

    private(set) var removeCallCount = 0
    var removeHandler: ((String) -> ())?
    func remove(with assetId: String)  {
        removeCallCount += 1
        if let removeHandler = removeHandler {
            removeHandler(assetId)
        }
        
    }
}

class AssetsManagerSubscriberProtocolMock: AssetsManagerSubscriberProtocol {
    init() { }


    private(set) var assetDidAddToWatchlistCallCount = 0
    var assetDidAddToWatchlistHandler: ((AssetEntity) -> ())?
    func assetDidAddToWatchlist(_ asset: AssetEntity)  {
        assetDidAddToWatchlistCallCount += 1
        if let assetDidAddToWatchlistHandler = assetDidAddToWatchlistHandler {
            assetDidAddToWatchlistHandler(asset)
        }
        
    }

    private(set) var assetDidRemoveFromWatchlistCallCount = 0
    var assetDidRemoveFromWatchlistHandler: ((AssetEntity) -> ())?
    func assetDidRemoveFromWatchlist(_ asset: AssetEntity)  {
        assetDidRemoveFromWatchlistCallCount += 1
        if let assetDidRemoveFromWatchlistHandler = assetDidRemoveFromWatchlistHandler {
            assetDidRemoveFromWatchlistHandler(asset)
        }
        
    }
}
