# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Coiner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coiner
  pod 'Swinject', '~> 2.8'
  pod 'SnapKit', '~> 5.0'

end
